name: ankabootmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  adaptix: 0.1.0
  cupertino_icons: 1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: 3.0.1
  get_it: 7.6.0
  http: 1.0.0
  injectable: 2.1.1
  injectable_generator: 2.1.5
  intl: 0.18.1
  mockito: ^5.4.2
  shared_preferences: 2.1.1

dependency_overrides:
  http: 0.13.5

dev_dependencies:
  build_runner: 2.4.4
  dart_code_metrics: 5.7.4
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
